In [ ]:
聊到深度学习, 大家第一感觉就是很高大上。
就像我们曾经说到机器学习，很多人也是感觉很高大上，但是慢慢接触之后，发现其无非是数学+编程实现，所以从线性回归开始，不断学习，把各种机器学习方法都学习了一遍，并能够通过Python的sklearn库编程实现。
有很多朋友和我聊到学习深度学习这个事情，我会推荐他们去看一些相关理论算法，从CNN、RNN到LSTM，从各种传统的深度学习网络结构到比较新的网络结构。在这个过程中发现了一点，就是他们看完了网络结构和算法原理后，往往难以下手去操作，因为Python使用sklearn库实现机器学习的流程非常方便，而且学习了Python的numpy、pandas基础即可快速上手，而深度学习的编程则需要更上一层，对Python新手不太友好，基础部分的张量各种操作和计算图编程都会让新手头大，而深度学习还面临着选择深度学习框架的问题，可供我们选择的框架实在太多，例如较为流行的Tensorflow、Pytorch、Keras、Mxnet、PaddlePaddle等等。各种相关的书也是如雨后春笋般出版出来，我翻看过一些书，还看过一些目录，发现了一个现象，就是各种深度学习框架书在对应的深度学习框架基础部分讲解往往不够详细，让人看完觉得跳跃感很大，而过于强调各种网络结构的实现，这十分不利于新手进行学习。而且初学者会了解到深度学习需要使用GPU训练模型，对于没有GPU配置的初学者，往往觉得学习之路出现了第一道坎，而对于有GPU的初学者，往往因为GPU环境搭建太复杂而从入门到放弃。其实没有GPU环境，也是可以进行深度学习编程学习的。

### pytorch引入

In [1]:
import torch
import numpy as np

### 创建张量

In [2]:
arr = np.ones((3,3))
print("数据类型为：",arr.dtype)
t = torch.tensor(arr)
print(t)

数据类型为： float64
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


### 创建张量

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)
print(arr)
print(t)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


### 修改张量

In [5]:
arr = np.array([[1,2,3],[4,5,6]])
t = torch.from_numpy(arr)

#修改array内容
arr[0,0] = 999

print(arr)
print(t)

[[999   2   3]
 [  4   5   6]]
tensor([[999,   2,   3],
        [  4,   5,   6]], dtype=torch.int32)


In [6]:
t1 = torch.tensor([1,2,3])#创建一个t1张量，赋一个初始值
t = torch.zeros((2,3),out=t1)#将创建的t张量输出到t1
print(t,'\n',t1)
print(id(t),id(t1),id(t)==id(t1))

tensor([[0, 0, 0],
        [0, 0, 0]]) 
 tensor([[0, 0, 0],
        [0, 0, 0]])
2084605375816 2084605375816 True


In [7]:
input = torch.empty(3, 5)
t = torch.zeros_like(input)
print(t)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [8]:
t = torch.full((2,2),8)
print(t)

tensor([[8., 8.],
        [8., 8.]])


In [9]:
input = torch.empty(3, 5)
t = torch.full_like(input,8)
print(t)

tensor([[8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.],
        [8., 8., 8., 8., 8.]])


In [10]:
t = torch.arange(1,9,2)
print(t)

tensor([1, 3, 5, 7])


In [11]:
t = torch.linspace(1,9,7)
print(t)

tensor([1.0000, 2.3333, 3.6667, 5.0000, 6.3333, 7.6667, 9.0000])


In [12]:
t = torch.logspace(start=-5, end=10,steps=4)
print(t)

tensor([1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


In [13]:
t = torch.eye(4)
print(t)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### 生成正态分布数据的张量

In [14]:
#mean为张量，std为张量
mean = torch.arange(1,6,dtype=torch.float)
std = torch.arange(1,6,dtype=torch.float)
t = torch.normal(mean,std)
print("mean:{},std:{}".format(mean,std))
print(t)

mean:tensor([1., 2., 3., 4., 5.]),std:tensor([1., 2., 3., 4., 5.])
tensor([ 1.5956, -0.9349,  1.7945,  8.0524,  7.9456])


In [15]:
#mean为标量，std为标量
t = torch.normal(0.2,1.0,size=(5,))
print(t)

tensor([ 1.1192, -0.1618,  1.2117, -0.4006,  0.6756])


In [16]:
#mean为标量，std为张量
mean = 2
std = torch.arange(1,4,dtype=torch.float)
t = torch.normal(mean,std)
print("mean:{},std:{}".format(mean,std))
print(t)

mean:2,std:tensor([1., 2., 3.])
tensor([ 2.5615,  2.2416, -1.5931])


In [17]:
#mean为张量，std为标量
mean = torch.arange(1,4,dtype=torch.float)
std = 2
t = torch.normal(mean,std)
print("mean:{},std:{}".format(mean,std))
print(t)

mean:tensor([1., 2., 3.]),std:2
tensor([-0.9332,  3.0824,  1.1787])


### 标准正态分布数据的张量

In [18]:
torch.randn(6)

tensor([-0.6828,  0.3659, -0.3481,  0.2043, -1.3155, -0.5559])

In [19]:
a = torch.ones((3,4))
t = torch.randn_like(a)
print(t)

tensor([[-1.3571e-01, -2.4681e-01, -7.6430e-01, -1.5986e+00],
        [ 8.1159e-04, -2.8634e-01, -3.8962e-01,  1.1206e+00],
        [-1.5792e+00,  1.0334e+00, -1.2379e+00,  1.3063e+00]])


In [20]:
torch.rand(3,4)

tensor([[0.3216, 0.4315, 0.6821, 0.8690],
        [0.2943, 0.2675, 0.7112, 0.8871],
        [0.3668, 0.3642, 0.5212, 0.2390]])

In [21]:
torch.randint(2, 6, (4,))

tensor([4, 2, 5, 5])

In [22]:
torch.randint(9, (3, 2))

tensor([[7, 2],
        [7, 2],
        [8, 7]])

In [23]:
torch.randperm(6)

tensor([0, 3, 1, 5, 4, 2])

In [25]:
a = torch.empty(3, 3).uniform_(0, 1)
a

tensor([[0.8743, 0.3144, 0.0818],
        [0.0236, 0.0744, 0.3838],
        [0.5188, 0.8553, 0.4509]])

In [26]:
torch.bernoulli(a)#使用上面创建的张量a作为概率值创建伯努利分布

tensor([[1., 0., 0.],
        [0., 0., 0.],
        [1., 0., 0.]])

### 张量的拼接

In [27]:
t = torch.ones((3,2))
t0 = torch.cat([t,t],dim=0)#在第0个维度上拼接
t1 = torch.cat([t,t],dim=1)#在第1个维度上拼接
print(t0,'\n\n',t1)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]) 

 tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [28]:
t2 = torch.cat([t,t,t],dim=0)
t2

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [29]:
t = torch.ones((3,2))
t1 = torch.stack([t,t],dim=2)#在新创建的维度上进行拼接
print(t1,t1.shape) #拼接完会从2维变成3维

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]) torch.Size([3, 2, 2])


In [30]:
t = torch.ones((3,2))
t1 = torch.stack([t,t],dim=0)#在新创建的维度上进行拼接
#由于指定是第0维，会把原来的3，2往后移动一格，然后在新的第0维创建新维度进行拼接
print(t1,t1.shape)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]]) torch.Size([2, 3, 2])


### 张量的切分

####  使用torch.chunk()切分

In [32]:
a = torch.ones((5,2))
t = torch.chunk(a,dim=0,chunks=2)#在5这个维度切分，切分成2个张量
for idx, t_chunk in enumerate(t):
    print(idx,t_chunk,t_chunk.shape)

0 tensor([[1., 1.],
        [1., 1.],
        [1., 1.]]) torch.Size([3, 2])
1 tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


#### 使用torch.split()切分

In [34]:
a = torch.ones((5,2))
t = torch.split(a,2,dim=0)#指定了每个张量的长度为2
for idx, t_split in enumerate(t):
    print(idx,t_split,t_split.shape)#切出3个张量

0 tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
1 tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
2 tensor([[1., 1.]]) torch.Size([1, 2])


In [35]:
a = torch.ones((5,2))
t = torch.split(a,[2,1,2],dim=0)#指定了每个张量的长度为列表中的大小【2，1，2】
for idx, t_split in enumerate(t):
    print(idx,t_split,t_split.shape)#切出3个张量

0 tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])
1 tensor([[1., 1.]]) torch.Size([1, 2])
2 tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


### 张量的索引

In [37]:
t = torch.randint(0,12,size=(4,3))
mask = t.ge(6) #ge是greater than or equal ,gt是greater than , le   lt 
t_select = torch.masked_select(t,mask)
print(t,'\n',mask,'\n',t_select)#将大于等于6的数据挑出来，返回一维张量

tensor([[ 0,  2,  5],
        [ 5,  3,  6],
        [ 4, 11,  6],
        [ 8,  7,  5]]) 
 tensor([[False, False, False],
        [False, False,  True],
        [False,  True,  True],
        [ True,  True, False]]) 
 tensor([ 6, 11,  6,  8,  7])


In [38]:
t = torch.randperm(10)
t1 = torch.reshape(t,(2,5))
print(t,'\n',t1)

tensor([3, 8, 0, 1, 9, 2, 6, 5, 7, 4]) 
 tensor([[3, 8, 0, 1, 9],
        [2, 6, 5, 7, 4]])


In [39]:
t1 = torch.reshape(t,(-1,5))# -1代表根据其他维度计算得到
print(t,'\n',t1)

tensor([3, 8, 0, 1, 9, 2, 6, 5, 7, 4]) 
 tensor([[3, 8, 0, 1, 9],
        [2, 6, 5, 7, 4]])


In [40]:
t = torch.randperm(10)
t[0] = 1024
print(t,'\n',t1)
print(id(t.data),id(t1.data))
#共享内存，id相同

tensor([1024,    1,    5,    2,    6,    8,    9,    7,    0,    3]) 
 tensor([[3, 8, 0, 1, 9],
        [2, 6, 5, 7, 4]])
2084622541192 2084622541192


In [41]:
t = torch.rand((4,3,2))
t1 = torch.transpose(t,dim0=0,dim1=1)#交换他们的第0，1维度
print(t.shape,t1.shape)

torch.Size([4, 3, 2]) torch.Size([3, 4, 2])


In [42]:
x = torch.randn(3,2)
print(x)
torch.t(x)

tensor([[-1.4659,  2.2305],
        [ 0.0881,  1.6183],
        [ 0.7413, -0.6628]])


tensor([[-1.4659,  0.0881,  0.7413],
        [ 2.2305,  1.6183, -0.6628]])

In [43]:
t = torch.rand((1,2,1,1))
t1 = torch.squeeze(t)
t2 = torch.squeeze(t,dim=0)
t3 = torch.squeeze(t,dim=1)#指定的轴长度不为1，不能移除
print(t.shape,'\n',t1.shape,t2.shape,t3.shape)

torch.Size([1, 2, 1, 1]) 
 torch.Size([2]) torch.Size([2, 1, 1]) torch.Size([1, 2, 1, 1])


In [44]:
x = torch.tensor([1, 2, 3, 4, 5])
torch.unsqueeze(x, 0)

tensor([[1, 2, 3, 4, 5]])